[package]
name = "ai-providers"
version = "0.1.0"
edition = "2024"

[dependencies]
ai-types = { version = "0.2", path = "../ai_types"}
zenwave = { path = "../zenwave" }
serde = { version = "1.0", features = ["derive"] }
futures-util = "0.3"
thiserror = "2.0.12"
serde_json = "1.0.141"
async-stream = "0.3"

[lib]
crate-type = ["lib"]

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }

[features]
integration-tests = []
